---
all:
  children:
    challenge_servers:
      hosts:
        challenge.tresorhaus-sec.de:
          ansible_host: your_server_ip
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
