---
- hosts: challenge_servers
  become: yes
  vars:
    app_dir: /opt/tresorhaus-challenge
    docker_network: challenge_net
    base_port: 2222

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - docker.io
          - python3
          - python3-pip
          - git
          - openssh-server
        state: present

    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'

    - name: Clone repository
      git:
        repo: "https://github.com/yourusername/tresorhaus-challenge.git"
        dest: "{{ app_dir }}"
        version: main

    - name: Create Docker network
      docker_network:
        name: "{{ docker_network }}"
        state: present

    - name: Build challenge base image
      docker_image:
        name: challenge-env
        build:
          path: "{{ app_dir }}"
        source: build

    - name: Copy systemd service file
      template:
        src: templates/tresorhaus-challenge.service.j2
        dest: /etc/systemd/system/tresorhaus-challenge.service
        mode: '0644'

    - name: Start and enable service
      systemd:
        name: tresorhaus-challenge
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Setup cleanup cron job
      cron:
        name: "cleanup old challenge containers"
        minute: "0"
        hour: "*/4"
        job: "docker rm -f $(docker ps -a --filter 'name=challenger_' --filter 'created=24h' -q)"
